server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    auth_basic "Developer Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # proxy API calls to backend
    location = /predict {
        proxy_pass http://backend:8000/predict;
        proxy_set_header Host $host;
        proxy_set_header Content-Type application/json;
    }

    location /submit_feedback {
        proxy_pass http://backend:8000/submit_feedback;
        proxy_set_header Host $host;
        proxy_set_header Content-Type application/json;
    }

    location /health {
        proxy_pass http://backend:8000/health;
    }

    location /ready {
        proxy_pass http://backend:8000/ready;
    }

    location /feedback_stats {
        proxy_pass http://backend:8000/feedback_stats;
    }

    location /metrics {
        proxy_pass http://backend:8000/metrics;
    }

    location /pipeline/ {
        proxy_pass http://ml_pipeline:8001/;
    }
}
